export const DIRECT_BANKS = [
  { name: "Kotak Mahindra Bank", id: "162", method: "DIRECT" },
  { name: "HDFC Bank Limited", id: "HDF", method: "DIRECT" },
  { name: "ICICI Bank", id: "ICI", method: "DIRECT" },
  { name: "State Bank of India", id: "SBI", method: "DIRECT" },
  { name: "Axis Bank", id: "UTI", method: "DIRECT" },
  { name: "YES Bank", id: "YBK", method: "DIRECT" },
  { name: "IndusInd Bank", id: "IDS", method: "DIRECT" },
];

export const NODAL_BANKS = [
  { name: "Andhra Bank", id: "ADB", mergedTo: "UBI", method: "NODAL" },
  { name: "Andhra Bank Corporate", id: "ADC", method: "NODAL" },
  { name: "Allahabad Bank", id: "ALB", mergedTo: "INB", method: "NODAL" },
  { name: "Allahabad Bank Corporate", id: "ALC", method: "NODAL" },
  { name: "Andhra Pragathi Grameena Bank", id: "APG", method: "NODAL" },
  { name: "AU Small Finance Bank", id: "AUB", method: "NODAL" },
  { name: "Axis Bank Corporate", id: "AXC", method: "NODAL" },
  { name: "Bank of Baroda-Corporate", id: "BBC", method: "NODAL" },
  { name: "Bank of Bahrain and Kuwait", id: "BBK", method: "NODAL" },
  { name: "Bank of Baroda- Retail", id: "BBR", method: "NODAL" },
  { name: "Bassein Catholic Bank", id: "BCB", method: "NODAL" },
  { name: "Bandhan Bank Corporate", id: "BDC", method: "NODAL" },
  { name: "Bandhan Bank", id: "BDN", method: "NODAL" },
  { name: "Bank Of India", id: "BOI", method: "NODAL" },
  { name: "Bank of Maharashtra", id: "BOM", method: "NODAL" },
  { name: "Central Bank of India", id: "CBI", method: "NODAL" },
  { name: "Canara Bank", id: "CNB", method: "NODAL" },
  { name: "Capital Bank", id: "CPB", method: "NODAL" },
  { name: "Cosmos Bank", id: "COB", method: "NODAL" },
  { name: "Corporate Punjab National Bank", id: "CPN", method: "NODAL" },
  { name: "Corporation Bank Corporate", id: "CR2", method: "NODAL" },
  { name: "Corporation Bank", id: "CRP", mergedTo: "UBI", method: "NODAL" },
  { name: "Catholic Syrian Bank", id: "CSB", method: "NODAL" },
  { name: "City Union Bank", id: "CUB", method: "NODAL" },
  { name: "Deutsche Bank", id: "DBK", method: "NODAL" },
  { name: "DIGI Bank", id: "DBS", method: "NODAL" },
  { name: "Development Credit Bank", id: "DCB", method: "NODAL" },
  {
    name: "Dena Bank Net Banking",
    id: "DEN",
    mergedTo: "BBR",
    method: "NODAL",
  },
  { name: "Dhanlakshmi Bank Corporate", id: "DL2", method: "NODAL" },
  { name: "Dhanlakshmi Bank", id: "DLB", method: "NODAL" },
  { name: "Equitas Bank", id: "EQB", method: "NODAL" },
  { name: "ESAF Small Finance Bank", id: "ESF", method: "NODAL" },
  { name: "Federal Bank", id: "FBK", method: "NODAL" },
  { name: "Fincare Small Finance Bank", id: "FNC", method: "NODAL" },
  { name: "HDFC UPI", id: "HD4", method: "NODAL" },
  { name: "Gujarat State Cooperative Bank", id: "GSB", method: "NODAL" },
  { name: "HSBC", id: "HSB", method: "NODAL" },
  { name: "UPI", id: "IC4", method: "NODAL" },
  { name: "IDBI Bank", id: "IDB", method: "NODAL" },
  { name: "IDBI Bank Corporate", id: "IDC", method: "NODAL" },
  { name: "IDFC Bank Netbanking", id: "IDN", method: "NODAL" },
  { name: "Indian Bank", id: "INB", method: "NODAL" },
  { name: "Indian Overseas Bank", id: "IOB", method: "NODAL" },
  { name: "Jammu & Kashmir Bank Limited", id: "JKB", method: "NODAL" },
  { name: "Jana Small Finance Bank", id: "JNB", method: "NODAL" },
  { name: "Janata Sahakari Bank", id: "JSB", method: "NODAL" },
  { name: "Karnataka Bank", id: "KBL", method: "NODAL" },
  { name: "Kalupur Coop Bank", id: "KLB", method: "NODAL" },
  { name: "Karur Vysya Bank Limited", id: "KVB", method: "NODAL" },
  { name: "Karnataka Vikas Gramin Bank", id: "KVG", method: "NODAL" },
  { name: "Lakshmi Vilas Bank Corporate", id: "LVC", method: "NODAL" },
  { name: "Lakshmi Vilas Bank Retail", id: "LVR", method: "NODAL" },
  { name: "Maharashtra Gramin Bank", id: "MGB", method: "NODAL" },
  { name: "North East Small Finance Bank", id: "NEB", method: "NODAL" },
  { name: "NKGSB Bank", id: "NKB", method: "NODAL" },
  { name: "Nutan Nagarik Sahakari Bank", id: "NUT", method: "NODAL" },
  {
    name: "ORIENTAL BANK OF COMMERCE",
    id: "OBC",
    mergedTo: "PNB",
    method: "NODAL",
  },
  { name: "Pragathi Krishna Bank", id: "PKB", method: "NODAL" },
  { name: "Punjab National Bank", id: "PNB", method: "NODAL" },
  { name: "Punjab and Sind Bank", id: "PSB", method: "NODAL" },
  { name: "Ratnakar Bank", id: "RBL", method: "NODAL" },
  { name: "RBL Bank Coporate", id: "RTC", method: "NODAL" },
  { name: "SCB Net Banking", id: "SCB", method: "NODAL" },
  { name: "South Indian Bank Ltd", id: "SIB", method: "NODAL" },
  { name: "SBM Bank", id: "SOM", method: "NODAL" },
  { name: "Suryoday Small Finance Bank", id: "SRB", method: "NODAL" },
  { name: "Surat Bank", id: "SUR", method: "NODAL" },
  { name: "Sutex Bank", id: "SUT", method: "NODAL" },
  { name: "Shamrao Vithal Bank Corporate", id: "SV2", method: "NODAL" },
  { name: "Shamrao Vithal Co.Operative Bank Ltd", id: "SVC", method: "NODAL" },
  { name: "Saraswat Bank", id: "SWB", method: "NODAL" },
  { name: "Syndicate Bank", id: "SYD", mergedTo: "CNB", method: "NODAL" },
  { name: "Thane Bharat Sahakari Bank", id: "TBB", method: "NODAL" },
  { name: "TJSB", id: "TJB", method: "NODAL" },
  { name: "Tamilnad Mercantile Bank Ltd", id: "TMB", method: "NODAL" },
  { name: "TNSC Bank", id: "TNC", method: "NODAL" },
  { name: "Union Bank of India", id: "UBI", method: "NODAL" },
  { name: "Union Bank of India Corporate", id: "UB2", method: "NODAL" },
  { name: "UCO Bank", id: "UCO", method: "NODAL" },
  { name: "United Bank of India", id: "UNI", mergedTo: "PNB", method: "NODAL" },
  { name: "Ujjivan Bank", id: "UJV", method: "NODAL" },
  { name: "Utkarsh Bank", id: "UTK", method: "NODAL" },
  { name: "Vijaya Bank", id: "VJB", mergedTo: "BBR", method: "NODAL" },
  { name: "Varachaa Bank", id: "VRB", method: "NODAL" },
  { name: "YES Bank Corporate", id: "YBC", method: "NODAL" },
  { name: "The Zoroastrian Co-op Bank", id: "ZOB", method: "NODAL" },
];

export const UPI_BANKS = [
  { name: "ABHYUDAYA COOPERATIVE BANK LIMITED", id: "ACB", method: "UPI" },
  { name: "ADITYA BIRLA IDEA PAYMENTS BANK LTD", id: "ABPB", method: "UPI" },
  { name: "AIRTEL PAYMENTS BANK LIMITED", id: "AIRP", method: "UPI" },
  { name: "ALLAHABAD BANK", id: "ALD", method: "UPI" },
  { name: "Allahabad Bank - Retail Net Banking", id: "ALB", method: "UPI" },
  { name: "ALLAHABAD BANK CORPORATE", id: "ALC", method: "UPI" },
  { name: "Andhra Bank", id: "ADB", method: "UPI" },
  { name: "ANDHRA PRADESH GRAMEENA VIKAS BANK", id: "APGX", method: "UPI" },
  { name: "ANDHRA PRAGATHI GRAMEENA BANK", id: "APG", method: "UPI" },
  { name: "APNA SAHAKARI BANK LIMITED", id: "ASB", method: "UPI" },
  { name: "AU SMALL FINANCE BANK", id: "AUB", method: "UPI" },
  { name: "Axis Bank", id: "UTI", method: "UPI" },
  { name: "BANDHAN BANK LIMITED", id: "BDB", method: "UPI" },
  { name: "Bank of Baroda - Corporate Banking", id: "BBC", method: "UPI" },
  { name: "Bank of Baroda - Retail Net Banking", id: "BBR", method: "UPI" },
  { name: "Bank Of India", id: "BOI", method: "UPI" },
  { name: "Bank of Maharashtra", id: "BOM", method: "UPI" },
  { name: "BASSEIN CATHOLIC COOPERATIVE BANK LIMITED", id: "BAC", method: "UPI" },
  { name: "Canara Bank", id: "CNB", method: "UPI" },
  { name: "Catholic Syrian Bank", id: "CSB", method: "UPI" },
  { name: "Central Bank of India", id: "CBI", method: "UPI" },
  { name: "CITI BANK", id: "CIT", method: "UPI" },
  { name: "CITY UNION BANK LIMITED", id: "CUB", method: "UPI" },
  { name: "Corporation Bank", id: "CRP", method: "UPI" },
  { name: "DCB BANK LIMITED", id: "DCB", method: "UPI" },
  { name: "Dena Bank", id: "DEN", method: "UPI" },
  { name: "DEVELOPMENT BANK OF SINGAPORE", id: "DBS", method: "UPI" },
  { name: "Dhanlakshmi Bank", id: "DLB", method: "UPI" },
  { name: "DOMBIVLI NAGARI SAHAKARI BANK LIMITED", id: "DNS", method: "UPI" },
  { name: "Equitas Small Finance Bank Ltd", id: "EQB", method: "UPI" },
  { name: "Equitas Small Finance Bank Ltd", id: "ESF", method: "UPI" },
  { name: "Federal Bank", id: "FBK", method: "UPI" },
  { name: "FINO PAYMENTS BANK LTD", id: "FINO", method: "UPI" },
  { name: "G P PARSIK BANK", id: "PJS", method: "UPI" },
  { name: "HDFC BANK", id: "HDF", method: "UPI" },
  { name: "HSBC BANK", id: "HSB", method: "UPI" },
  { name: "ICICI Bank - Retail Net Banking", id: "ICI", method: "UPI" },
  { name: "IDBI Bank - Retail Net Banking", id: "IDB", method: "UPI" },
  { name: "IDFC BANK LIMITED", id: "IDF", method: "UPI" },
  { name: "Indian Bank", id: "INB", method: "UPI" },
  { name: "Indian Overseas Bank", id: "IOB", method: "UPI" },
  { name: "IndusInd Bank", id: "IDS", method: "UPI" },
  { name: "JALGAON JANATA SAHAKARI BANK LIMITED", id: "JJS", method: "UPI" },
  { name: "Jammu & Kashmir Bank", id: "JKB", method: "UPI" },
  { name: "Janata Sahakari Bank", id: "JSB", method: "UPI" },
  { name: "JIO PAYMENTS BANK LIMITED", id: "JIOP", method: "UPI" },
  { name: "KALLAPPANNA AWADE ICHALKARANJI JANATA SAHAKARI BANK LIMITED", id: "KAI", method: "UPI" },
  { name: "KALYAN JANATA SAHAKARI BANK", id: "KJS", method: "UPI" },
  { name: "KAPOL COOPERATIVE BANK LIMITED", id: "KCB", method: "UPI" },
  { name: "Karnataka Bank Ltd", id: "KBL", method: "UPI" },
  { name: "KARNATAKA VIKAS GRAMEENA BANK", id: "KVG", method: "UPI" },
  { name: "Karur Vysya Bank", id: "KVB", method: "UPI" },
  { name: "KERALA GRAMIN BANK", id: "KLG", method: "UPI" },
  { name: "Kotak Bank", id: "162", method: "UPI" },
  { name: "Lakshmi Vilas Bank", id: "LVB", method: "UPI" },
  { name: "Laxmi Vilas Bank - Corporate Net Banking", id: "LVC", method: "UPI" },
  { name: "Laxmi Vilas Bank - Retail Net Banking", id: "LVR", method: "UPI" },
  { name: "MAHANAGAR COOPERATIVE BANK", id: "MCB", method: "UPI" },
  { name: "MAHARASHTRA GRAMIN BANK", id: "MGBX", method: "UPI" },
  { name: "NKGSB BANK", id: "NKB", method: "UPI" },
  { name: "Oriental Bank of Commerce", id: "OBC", method: "UPI" },
  { name: "PAYTM PAYMENTS BANK LTD", id: "PYTM", method: "UPI" },
  { name: "PRAGATHI KRISHNA GRAMIN BANK", id: "PKG", method: "UPI" },
  { name: "PRATHAMA BANK", id: "PRT", method: "UPI" },
  { name: "Punjab & Maharastra Coop Bank", id: "PMC", method: "UPI" },
  { name: "Punjab & Sind Bank", id: "PSB", method: "UPI" },
  { name: "Punjab National Bank - Corporate Banking", id: "CPN", method: "UPI" },
  { name: "Punjab National Bank - Retail Net Banking", id: "PNB", method: "UPI" },
  { name: "RAJKOT NAGRIK SAHAKARI BANK LIMITED", id: "RNS", method: "UPI" },
  { name: "Ratnakar Bank - Retail Net Banking", id: "RBL", method: "UPI" },
  { name: "RBL Bank Limited", id: "RAT", method: "UPI" },
  { name: "Saraswat Bank", id: "SWB", method: "UPI" },
  { name: "SHAMRAO VITHAL BANK CORPORATE", id: "SV2", method: "UPI" },
  { name: "South Indian Bank", id: "SIB", method: "UPI" },
  { name: "Standard Chartered Bank", id: "SCB", method: "UPI" },
  { name: "State Bank of India", id: "SBI", method: "UPI" },
  { name: "SUTEX COOPERATIVE BANK LIMITED", id: "SUT", method: "UPI" },
  { name: "Syndicate Bank", id: "SYD", method: "UPI" },
  { name: "Tamilnad Mercantile Bank Ltd.", id: "TMB", method: "UPI" },
  { name: "TELANGANA STATE COOP APEX BANK", id: "TSA", method: "UPI" },
  { name: "THE COSMOS CO OPERATIVE BANK LIMITED", id: "COS", method: "UPI" },
  { name: "THE GUJARAT STATE COOPERATIVE BANK LIMITED", id: "GSC", method: "UPI" },
  { name: "THE HASTI COOP BANK LTD", id: "HCB", method: "UPI" },
  { name: "THE MEHSANA URBAN COOPERATIVE BANK", id: "MSN", method: "UPI" },
  { name: "THE NAINITAL BANK LIMITED", id: "NTB", method: "UPI" },
  { name: "THE NAV JEEVAN CO-OP BANK LTD.", id: "NJCX", method: "UPI" },
  { name: "THE SHAMRAO VITHAL COOPERATIVE BANK", id: "SVC", method: "UPI" },
  { name: "THE SURAT PEOPLES COOPERATIVE BANK LIMITED", id: "SPC", method: "UPI" },
  { name: "THE TAMIL NADU STATE APEX COOPERATIVE BANK", id: "TNS", method: "UPI" },
  { name: "THE THANE BHARAT SAHAKARI BANK LIMITED", id: "TBS", method: "UPI" },
  { name: "THE VARACHHA COOPERATIVE BANK LIMITED", id: "VAR", method: "UPI" },
  { name: "THE VIJAY CO OPERATIVE BANK LTD.", id: "VIJX", method: "UPI" },
  { name: "THE VISHWESHWAR SAHAKARI BANK LIMITED", id: "VSB", method: "UPI" },
  { name: "TJSB Bank", id: "TJB", method: "UPI" },
  { name: "TJSB SAHAKARI BANK LTD", id: "TJS", method: "UPI" },
  { name: "UCO Bank", id: "UCO", method: "UPI" },
  { name: "Ujjivan Small Finance Bank Limited", id: "UJV", method: "UPI" },
  { name: "Union Bank of India", id: "UBI", method: "UPI" },
  { name: "United Bank of India", id: "UNI", method: "UPI" },
  { name: "VASAI VIKAS SAHAKARI BANK LIMITED", id: "VVS", method: "UPI" },
  { name: "Vijaya Bank", id: "VJB", method: "UPI" }
];

export const Direct_Plan = [...DIRECT_BANKS, ...NODAL_BANKS];